### ISSUE TITLE
support for arbitrary projections (unlink from Web Mercator)

### ISSUE THREAD

**Issue by nvkelso** [migurski/Dymo#17]
Albers, Lambert, and UTM would be most useful.

**Comment by migurski** [comment]
Agree agree.

**Comment by migurski** [comment]
Two new parameters to dymo-label.py: --scale is a floating point value, --projection is a PROJ.4 string.

Passing --scale and --zoom is an error. Passing --projection and no --scale defaults to scale=1.0. Passing --projection and --zoom is an error.

One new output parameter to dymo-label.py: --output-projected is a boolean to output projected coordinates.

**Comment by migurski** [comment]
Added in 0.9.0.
