### ISSUE TITLE
preprocessing flag for culling dense places

### ISSUE THREAD

**Issue by nvkelso** [migurski/Dymo#4]
optparser.add_option('-r', '--radius', dest='radius',
                     type='int', help='Pixel buffer around each place. Default value is %(radius)d.' % defaults)

**Comment by nvkelso** [comment]
Otherwise the temperature is 10k+ forever trying to include cities that are low priority at that zoom. Akin to the mapnik logic.

**Comment by migurski** [comment]
Fixed in 61ca2f9.
