### ISSUE TITLE
"make geojson" doesn't do anything.

### ISSUE THREAD

**Issue by keithbriggs** [migurski/Dymo#40]
The webpage says "Demo area: Run make geojson to anneal labels for San Francisco and Israel sample areas from zooms 4 to 10. This will automatically build the data files, too (eg: make data). Should run in less than an hour.".    But actually:

kbriggs:~/Downloads/Dymo-master> make geojson
make: `geojson' is up to date.

**Comment by nvkelso** [comment]
run it with
    make geojson -B
and that'll force it to run thru all the steps.

What it's telling you is there's nothing for make to do for `make geojson`,
because none of the dependencies have changed, and the geojson files are
packaged with the repo out of the box.

**Comment by keithbriggs** [comment]
Thanks  - now running!
Keith
