### ISSUE TITLE
Force 9-point orientation flag

### ISSUE THREAD

**Issue by nvkelso** [migurski/Dymo#6]
Force Orientation 9 point flag (UL, UC, UR, ML, MC, MR, BL, BC, BR)

Where
U = upper
M = middle
B = bottom
L = Left
C = Center
R = Right

NOTE: MC is currently not supported in Dymo at all. 

Useful when we want to force big cities at zooms to be center justified on their townspot, while everything else is anealed.

Useful when we want to force coastal cities into the ocean to allow for more labels in the land area.

**Comment by migurski** [comment]
Making some progress on this in 1cd8074b and a55710da. I've added support for six placement options: "top left", "top", "top right", "bottom left", "bottom", and "bottom right". "Left" and "right" don't really have any support currently and they seem insufficiently different from slightly-high and slightly-low, so I'm going to leave them off entirely. "Centered" is going to take some doing and I may leave it off until later. Last thing is to get these working from input files.
